version: 0.0
os: linux
files:
  - source: dist/
    destination: /var/www/web/
  - source: appspec.yml
    destination: appspec.yml
  - source: scripts/install_dependencies.sh
    destination: scripts/install_dependencies.sh
  - source: scripts/start_server.sh
    destination: scripts/start_server.sh
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
