version: 0.0
os: linux
files:
  - source: / # Source location in the deployment package
    destination: /var/www/web/ # Destination directory on the target instance
    overwrite: yes # Optional: Overwrites existing files

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
