version: 0.0
os: linux
files:
  - source: /dist/
    destination: /var/www/web/
  - source: /appspec.yml
    destination: /tmp/appspec.yml
  - source: /scripts/install_dependencies.sh
    destination: /tmp/scripts/install_dependencies.sh
  - source: /scripts/start_server.sh
    destination: /tmp/scripts/start_server.sh
hooks:
  AfterInstall:
    - location: /tmp/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /tmp/scripts/start_server.sh
      timeout: 300
      runas: root
