version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
artifacts:
  files:
    - appspec.yml            # Include the appspec.yml file
    - scripts/**/*           # Include everything inside the scripts/ directory
    - '**/*'
  base-directory: dist

