version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
artifacts:
  files:
    - '**/*'  # This includes everything in the repo
    - 'appspec.yml'  # Include the appspec.yml explicitly
    - 'scripts/**/*'  # Include any scripts in the scripts folder
  base-directory: dist  # Ensure only build output is in base-directory
                        # god bless you

